on:
  workflow_call:
    inputs:
      docker_build_args:
        required: false
        type: string
      docker_file_path:
        required: false
        default: "./"
        type: string
      image_name:
        required: true
        type: string
    secrets:
      dockerhub_user:
        required: true
      dockerhub_token:
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build the image
        run: docker build -t ${{ inputs.image_name }}:${{ github.sha }} --build-arg VERSION=${{ github.ref_name }} ${{ inputs.docker_build_args }} ${{ inputs.docker_file_path }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_token }}
      - name: Push image with commit SHA
        run: docker push ${{ inputs.image_name }}:${{ github.sha }}
      - name: Push image with tag
        if: "startsWith(github.ref, 'refs/tags/')"
        run: docker tag ${{ inputs.image_name }}:${{ github.sha }} ${{ inputs.image_name }}:${{ github.ref_name }} && \
             docker push ${{ inputs.image_name }}:${{ github.ref_name }}
        