on:
  workflow_call:
    inputs:
      workdir:
        required: false
        default: "./"
        type: string
      needs:
        required: false
        type: string
        default: '[]'
      services:
        required: false
        type: string
        default: '{}'
      env:
        required: false
        type: string
        default: '{}'

env:
  NEEDS: ${{ github.event.inputs.needs }}

jobs:
  test:
    needs: []
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    container:
      image: golang:1.22.5-alpine3.20
      options: --user root
    services: ${{ fromJSON(inputs.services) }}
    env: ${{ fromJSON(inputs.env) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Run tests
        run: go test -cover -race ${{ inputs.workdir }}...