on: push

permissions:
  # Required by golangci job to write annotations to the merge request.
  contents: read
  checks: write

jobs:
  golang_quality:
    uses: ./.github/workflows/golang_quality.yaml
    with:
      workdir: "tests/golang_quality/"