on: push

jobs:
  golang_test:
    uses: ./.github/workflows/golang_test.yaml
    with:
      workdir: "tests/golang_test/"
      services: '{"database": {"image": "mysql:8.0", "ports": ["3306:3306"]}}'
      env: '{"TESTENV": "value"}'