on:
  workflow_call:
    inputs:
      workdir:
        required: false
        default: "./"
        type: string

jobs:
  golangci:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: v1.22.5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          working-directory: "${{ inputs.workdir }}"
  go_tidy:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    container:
      image: cubicrootxyz/golang-ci:v1.22.5-3
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Run go mod tidy
        run: (cd ${{ inputs.workdir }} && go mod tidy)
      - name: Run git diff
        run: git diff --exit-code
  go_generate:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    container:
      image: cubicrootxyz/golang-ci:v1.22.5-3
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@v1.6.0
      - name: Run go generate
        run: go generate ${{ inputs.workdir }}...
      - name: Run git diff
        run: git diff --exit-code