on:
  workflow_call:
    inputs:
      workdir:
        required: false
        default: "./"
        type: string
      services:
        required: false
        type: string
        default: '{}'
      env:
        required: false
        type: string
        default: '{}'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cubicrootxyz/golang-ci:v1.24.2
      options: --user root
    services: ${{ fromJSON(inputs.services) }}
    env: ${{ fromJSON(inputs.env) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Run tests
        run: (cd ${{ inputs.workdir }} && CGO_ENABLED=1 && go test -cover -race ./...)