on:
  workflow_call:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: v1.22.5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59