on: push

jobs:
  openapi3_render_test_prep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - uses: actions/upload-artifact@master
        with:
          name: spec
          path: tests/openapi3/
  openapi3_render_test:
    needs: 
      - openapi3_render_test_prep
    uses: ./.github/workflows/openapi3_render.yaml
    with:
      spec_artifact_name: spec
      spec_artifact_path: tests/openapi3/
      spec_filename: petstore.yaml