on: 
  workflow_call:
    inputs:
      spec_artifact_name:
        required: true
        type: string
      spec_artifact_path:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "${{ github.ref == 'refs/heads/main' }}"
    steps:
      - uses: actions/download-artifact@master
        with:
          name: ${{ inputs.spec_artifact_name }}
          path: ${{ inputs.spec_artifact_path }}
      - name: Upload HTML file as pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.spec_artifact_path }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4