on: 
  workflow_call:
    inputs:
      author:
        required: false
        type: string
        default: "Renovate <renovate@users.noreply.github.com>"
    secrets:
      token:
        required: true

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Renovate
        uses: docker://renovate/renovate:latest
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_TOKEN: ${{ secrets.token }}
          RENOVATE_AUTOMERGE: "false"
          RENOVATE_ONBOARDING: "false"
          RENOVATE_GIT_AUTHOR: "${{ inputs.author }}"